### ISSUE TITLE
Should this API give UA's flexibility to return false if input is pending?

### ISSUE THREAD

**Issue by tdresser** [WICG/is-input-pending#1]
At TPAC, @rniwa expressed a desire to have some flexibility in what is returned from this method.

I can imagine going with a name like `isPriorityInputPending` to provide a bit of wiggle room. Or just
`isInputPending` if we don't need wiggle room.

There are two kinds of wiggle room we could provide:
1. The ability to return false when input is pending.
2. The ability to return true when input is not pending.

Ryosuke, would wiggle room of type 1 be enough, or would you also want type 2?

**Comment by smaug----** [comment]
I think the API should let UA to return false. So it may need renaming to something better.
isPriorityInputPending isn't really any better. What is "priority input". Priority of some event type depends on the application.

**Comment by n8schloss** [comment]
I think we addressed this in the current version of the spec.
