### ISSUE TITLE
navigator.scheduling or window.scheduling?

### ISSUE THREAD

**Issue by foolip** [WICG/is-input-pending#30]
The spec has an example with `navigator.scheduling`, but the IDL defines `window.scheduling`:
https://wicg.github.io/is-input-pending/#examples-of-usage
https://wicg.github.io/is-input-pending/#extensions-to-the-window-interface

The [Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/navigator_scheduling.idl) adds `navigator.scheduling`, so probably that's the intention in the spec too?

**Comment by acomminos** [comment]
Yes, that's correct! I've gone ahead and posted #31 to resolve this, thanks for the pointer.

**Comment by foolip** [comment]
Thanks @acomminos!
