### ISSUE TITLE
IsInputPendingOptions + IsInputPendingOptionsInit is extremely unusual and would benefit from performance measurements

### ISSUE THREAD

**Issue by domenic** [WICG/is-input-pending#35]
Hi folks,

The use of a class (IsInputPendingOptions) as an options argument is extremely unusual on the web platform. I see this is justified in the spec text with

> As isInputPending is expected to be called many times within a single frame, the API is designed to be as low overhead as possible. The presence of an options struct gives UAs the ability to optimize parameters, and thus reusing long-lived options objects is RECOMMENDED.

However, this is so extraordinarily un-web-platform-like, that I think it needs a corresponding amount of evidence before we should make it part of the platform.

Do you have benchmarks showing the impact of the IsInputPendingOptions approach, versus just using a dictionary? I.e. benchmarks showing the benefits of

```js
const options = new IsInputPendingOptions({ includeContinuous: true });

// Do this many times
navigator.scheduling.isInputPending(options);
```

versus

```js
const options = { includeContinuous: true };

// Do this many times
navigator.scheduling.isInputPending(options);
```

?

**Comment by acomminos** [comment]
Hey @domenic, thanks for the feedback! It's not necessarily the dictionary overhead in its current form that we were concerned about, but rather providing a usage signal to the UA.

Since isInputPending requires some form of asynchronous hit testing to determine what frame an event will be dispatched to, we wanted to give UAs the option to avoid doing such work if the API is unlikely to be used on a page. For example, if the implementation uses the compositor to perform this hit testing, we could use the lifetime of IsInputPendingOptions to signal to the compositor whether or not to perform this attribution for incoming events.

To your original point about dictionary overhead, it is possible that future extensions (e.g. taking in a list of event types to listen for) may have overhead that could be eliminated with an options object -- you could imagine the UA converting that list of event type strings into a bitmask for much faster checks. Though that wasn't the main motivation in the API's current form, it does manage to resolve both issues.

**Comment by domenic** [comment]
> For example, if the implementation uses the compositor to perform this hit testing, we could use the lifetime of IsInputPendingOptions to signal to the compositor whether or not to perform this attribution for incoming events.

Can you explain why they couldn't do the same with the dictionary object in my second example?

**Comment by acomminos** [comment]
> Can you explain why they couldn't do the same with the dictionary object in my second example?

Ah, so dictionary mutability turns out to be an issue here. Consider the case where `includeContinuous` is changed by script -- we can intercept this setter on the options class, but (correct me if I'm wrong) it's fairly unidiomatic to monitor such a change on dictionary objects.

**Comment by domenic** [comment]
I don't think that's particularly un-idiomatic. Especially compared to the web-developer-facing issue presented by the original post!

**Comment by domenic** [comment]
Note that you seem to be discussing the idiomaticness of a behind-the-scenes optimization in terms of whether it's idiomatic implementation code, whereas I'm discussing the idiomaticness of the web-developer-facing API. Right?

**Comment by acomminos** [comment]
> Note that you seem to be discussing the idiomaticness of a behind-the-scenes optimization in terms of whether it's idiomatic implementation code, whereas I'm discussing the idiomaticness of the web-developer-facing API. Right?

That's right, yeah. Considering the minor API changes required to make this possible (i.e. it doesn't invalidate the results of any of our prior trials), I'm open to the API surface proposed. I do agree that making this idiomatic to users is a preferable tradeoff.

BTW, your comment did get me thinking about dictionary overhead in general. I've proceeded with a local benchmark, which shows that using a dictionary vs. options class reduces performance by around ~25% in Blink. On a high end desktop, this is a reduction from ~507k ops/s to ~410k ops/s.

Considering this is intended to be called in a scheduler's hot loop, do you think improving DevEx is worth this performance hit?

**Comment by domenic** [comment]
That's hard for me to say, as I'm not as familiar with how many times per second this would typically be called, how optimizable that 20% is, and how much of an app's overall per-frame performance budget this would be taking up. You and other implementers would be best placed to answer that.

In general, though, I think it'd be best to start with the more idiomatic version, and then work on optimizations on top of that (e.g. hand-rolled bindings might be a low-hanging one). Only if that fails would I consider exposing the complexity to web developers, assuming there are web developers complaining about the performance who want to opt in to the extra complexity in exchange.

**Comment by acomminos** [comment]
> That's hard for me to say, as I'm not as familiar with how many times per second this would typically be called, how optimizable that 20% is, and how much of an app's overall per-frame performance budget this would be taking up. You and other implementers would be best placed to answer that.

Yeah that's fair, didn't mean to put you on the spot -- was just curious how strongly you thought this would be an activation win :)

Putting on my user hat: from React's perspective, we plan on calling this hundreds of times per frame. This is pretty significant overhead, considering that every 1000 invocations would be 1ms slower with this approach (and that's on a high end desktop!). We would very much prefer to avoid this if possible.

> In general, though, I think it'd be best to start with the more idiomatic version, and then work on optimizations on top of that (e.g. hand-rolled bindings might be a low-hanging one). Only if that fails would I consider exposing the complexity to web developers, assuming there are web developers complaining about the performance who want to opt in to the extra complexity in exchange.

Starting from a simpler API surface has a problem in that we lock in our users to a less performant solution that we'll have to support over the long run. Would it not be preferable to provide a simpler API once we determine that users are having activation issues? Especially considering with a dictionary, we're locking ourselves into performing key-value validation (at the very least).

(It's also worth noting that `IsInputPendingOptions` is optional, and the arg-less usage would likely suffice for most use cases.)

---

A side note, but I did find another API using a similar pattern (namely the [Push API](https://w3c.github.io/push-api/#pushsubscriptionoptions-interface)). Not that this makes this any less unusual.

**Comment by domenic** [comment]
No, I don't think so. You always want to provide the simpler API, and only saddle the web platform, and all the code written on top of it, with the more complex one if it turns out to be unoptomizable.

**Comment by domenic** [comment]
Also, I don't think it's good to make claims about the performance of the API at this point. You're in fact talking about the performance of a very specific implementation, which from what I understand isn't very optimized.

**Comment by yoavweiss** [comment]
IIRC, this API shape was proposed as a way to avoid an unoptimizable list of strings as input. A dictionary seems like something we can (and should) be able to optimize away. 

A 20% hit would be unfortunate, but might be worthwhile to reach out to Chromium binding experts to see if they have thoughts on how that can be improved.

**Comment by domenic** [comment]
You could also consider other API shapes, e.g. `isInputPending()` + `isContinuousInputPending()` or something. (Probably those names are bad...)

**Comment by acomminos** [comment]
> Also, I don't think it's good to make claims about the performance of the API at this point. You're in fact talking about the performance of a very specific implementation, which from what I understand isn't very optimized.

Totally agreed, I should've mentioned that my main concern was making the dynamic property lookup a lower bound for bindings performance. Looking at a native profile of the dict-based prototype I was using, it seems that this is indeed the main source of pain (~20% of cycles spent in `v8::Object::Get`).

As mentioned below, I'll try and solicit some advice here.

> IIRC, this API shape was proposed as a way to avoid an unoptimizable list of strings as input. A dictionary seems like something we can (and should) be able to optimize away.

Yup, thanks for the context Yoav -- this was indeed the original motivating factor behind the move.

> A 20% hit would be unfortunate, but might be worthwhile to reach out to Chromium binding experts to see if they have thoughts on how that can be improved.

Indeed, I'll reach out for some advice here. I do wonder if there are other performance-sensitive dictionary consuming APIs.

> You could also consider other API shapes, e.g. isInputPending() + isContinuousInputPending() or something. (Probably those names are bad...)

This definitely fits the current use cases, but I'd be worried that this wouldn't scale very well if we wanted to adapt the predicate over time (e.g. we find out that some sites may want to filter on a more specific class of inputs like "includeKeyboard", etc).

**Comment by acomminos** [comment]
I'd like to amend the previous benchmark numbers and conclusion reached -- using a Chromium build with full optimizations, we get around 1.7m runs/s with an options class or the no-args case, and 1.1m runs/s with a dict.

This makes me more comfortable with the viability of @domenic's suggestion, as it demonstrates that a performant enough implementation can exist with the proposed API surface. This is close enough (in absolute terms) to the performance of the default (no-args) case as well as the origin trial implementation to suggest that this won't compromise the efficacy of the API.

If the performance does end up bottlenecking us down the line, and we find ourselves unable to optimize after adding more supported keys, I can see a path to instantiating some kind of `PendingInputMonitor` class that accepts this dictionary as an alternative.

If there are no other objections, I'll post a PR to amend the spec accordingly :)

**Comment by n8schloss** [comment]
Sounds like this is resolved now :)
