### ISSUE TITLE
"false" is not a boolean

### ISSUE THREAD

**Issue by domenic** [WICG/is-input-pending#36]
https://wicg.github.io/is-input-pending/#isinputpendingoptionsinit

You are probably looking for `false`, not `"false"`.

**Comment by n8schloss** [comment]
haha, wow, not sure how we missed that. Will fix now, thanks!

**Comment by n8schloss** [comment]
Fixed at https://github.com/WICG/is-input-pending/commit/9d6a33c252de40cfe3250b55c5513a441e690e96
