### ISSUE TITLE
"event loop has any task queues that contain a task that will dispatch an event that is a UIEvent or TouchEvent or a child of either" is vague

### ISSUE THREAD

**Issue by smaug----** [WICG/is-input-pending#43]
"event loop has any task queues that contain a task that will dispatch an event that is a UIEvent or TouchEvent or a child of either"
is a bit vague.

window.addEventListener("message", function() { window.dispatchEvent(new MouseEvent('click')); });
window.postMessage("foo", "*");
adds a task which will dispatch a MouseEvent (which extends UIEvent). So per draft, user agent should somehow detect that the
task will dispatch that mouse event. I doubt anyone wants that.

Should the draft perhaps rely on 'user interaction task source'?

**Comment by Sheraff** [comment]
Maybe it should only include events that were generated by a user action, i.e. events for which `event.isTrusted` is true. I'm not sure at what point `isTrusted` becomes known but I'm just saying "same logic as for that variable".

**Comment by acomminos** [comment]
> Should the draft perhaps rely on 'user interaction task source'?

I think that this makes a lot of sense -- delegating to the HTML spec regarding which events are considered dispatched "in response to user input" is ideal, resolving the issue with synthetic events and mapping better to the problem space this spec aims to capture.

I'll write up a proposal PR for this.
