### ISSUE TITLE
click is not a pending input event type

### ISSUE THREAD

**Issue by smaug----** [WICG/is-input-pending#7]
the testcase uses click as pending event type, but click is dispatched based on mouseup.

**Comment by tdresser** [comment]
Or click can be dispatched due to a finger leaving the screen, etc.

We've decided to allow web developers to use the event names they're already familiar with to check if input is pending. @n8schloss, we probably should expand on this a bit in the explainer.

**Comment by tdresser** [comment]
"click" means that there is a pending set of events which, if not preventDefaulted, will result in a "click".

**Comment by tdresser** [comment]
Thanks for the example! We'll give this some though.

**Comment by n8schloss** [comment]
I think we resolved this.
